package com.pbj.v2.generation;

public enum ProblemFamily {
    SCALAR_ONLY,
    ARRAY,
    COMMAND_BASED,
    GRID,
    GRAPH_TREE,
    RANGE_QUERY_UPDATE,
    NUMERIC_OVERFLOW_STRESS,
    DYNAMIC_PROGRAMMING,
    NUMBER_THEORY,
    DATA_STRUCTURE,
    STRING,
    GENERAL,
    COMBINATORICS,
    CONSTRUCTIVE,
    DIGIT_PRODUCT_FACTORIZATION,
    GAME_THEORY,
    UNKNOWN
}
